redirect_uri = 'https://localhost'
chromedriver_path ='/Users/victorbotteicher/Desktop/PaperTradeCalculator/PaperTrader/chromedriver'
ACCESS_TOKEN = 'YourTradierApiTokenGoesHere'
API_BASE_URL = 'https://api.tradier.com/v1/'
SECRET_KEY = 'XXXXXXX'
